### ISSUE TITLE
Rework `index.md`

### ISSUE THREAD

**Issue by ocaisa** [hpc-carpentry/old-hpc-workflows#4]
This can only really be tackled once we have a better idea of the whole lesson but will include
- [x] Introducing the data we will create/use
- [x] Identifying the prereqs and where they can be found (and I notice now that HPC Carpentry will not fulfil the Python prereq...so how will we tackle this?)

**Comment by tkphd** [comment]
I'm hand-waving away the Python prereq because the Snakefile is its own language, in-between Make and Python. I know, it's weak.
In my head, the "data" we'll use is a script (matplotlib, gnuplot, or other) to plot the Amdahl data, which will be transformed from execution time vs. number of ranks to speedup vs. number of ranks by the plotting script.
Is that sensible?
